In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
titanic_df = pd.read_csv("./data/train.csv")
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
y_titanic_df = titanic_df["Survived"]
X_titanic_df = titanic_df.drop("Survived", axis=1)
X_titanic_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
X_titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Pclass       891 non-null    int64
 2   Name         891 non-null    str
 3   Sex          891 non-null    str
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    str
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    str
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 76.7 KB

In [10]:
test_df = pd.read_csv("./data/test.csv")

res = test_df["PassengerId"]

test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [8]:
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 36.1 KB

In [ ]:
#결측값 처리(1)

X_titanic_df["Age"] = X_titanic_df["Age"].fillna(X_titanic_df["Age"].mean())
X_titanic_df["Cabin"] = X_titanic_df["Cabin"].fillna("N")
X_titanic_df["Embarked"] = X_titanic_df["Embarked"].fillna("N")
X_titanic_df["Fare"] = X_titanic_df["Fare"].fillna(0)
X_titanic_df["Cabin"] = X_titanic_df["Cabin"].str[:1]


X_titanic_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [ ]:
#결측값 처리(2)
test_df["Age"] = test_df["Age"].fillna(X_titanic_df["Age"].mean())
test_df["Cabin"] = test_df["Cabin"].fillna("N")
test_df["Embarked"] = test_df["Embarked"].fillna("N")
test_df["Fare"] = test_df["Fare"].fillna(0)
test_df["Cabin"] = test_df["Cabin"].str[:1]


test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,N,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,N,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,N,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,N,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,N,S

In [13]:
# 다 다른 데이터 분류에 필요없는 데이터를 날림.

drop_col = ["PassengerId","Name","Ticket"]
X_titanic_df = X_titanic_df.drop(columns = drop_col)
test_df = test_df.drop(columns = drop_col)

In [14]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [18]:
oe = OrdinalEncoder(handle_unknown = "use_encoded_value", unknown_value=-1)
X_titanic_df[["Cabin","Sex","Embarked"]] = oe.fit_transform(X_titanic_df[["Cabin","Sex","Embarked"]])

test_df[["Cabin","Sex","Embarked"]] = oe.transform(test_df[["Cabin","Sex","Embarked"]])

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X_titanic_df, y_titanic_df, test_size = 0.2, random_state=42)

In [21]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

dt_clf = DecisionTreeClassifier(random_state = 42)
rf_clf = RandomForestClassifier(random_state = 42)
lr_clf = LogisticRegression(solver = "liblinear")

dt_clf.fit(X_train, y_train)
dt_pred = dt_clf.predict(X_valid)
print(accuracy_score(y_valid, dt_pred))

rf_clf.fit(X_train, y_train)
rf_pred = rf_clf.predict(X_valid)
print(accuracy_score(y_valid, rf_pred))

lr_clf.fit(X_train, y_train)
lr_pred = lr_clf.predict(X_valid)
print(accuracy_score(y_valid, lr_pred))

0.770949720670391
0.8044692737430168
0.7932960893854749

In [ ]:
dt_test = dt_clf.predict(test_df)

rf_test = rf_clf.predict(test_df)

lr_test = lr_clf.predict(test_df)


result = pd.DataFrame({"PassengerId": res, 
                        "DecisionTree" : dt_test,
                        "RandomForest" : rf_test,
                        "LogisticRegression" : lr_test
                       })

In [23]:
result.head()

   PassengerId  DecisionTree  RandomForest  LogisticRegression
0          892             1             1                   1
1          893             1             1                   1
2          894             1             1                   1
3          895             0             1                   1
4          896             0             1                   1

In [ ]:
result["DecisionTree"].value_counts() #데이터 프레임에 행이 많을때 각 행마다 무슨값이 들어가있는지 확인할때 (value_counts())

DecisionTree
1    308
0    110
Name: count, dtype: int64

In [25]:
result["RandomForest"].value_counts()

RandomForest
1    414
0      4
Name: count, dtype: int64

In [26]:
result["LogisticRegression"].value_counts()

LogisticRegression
1    418
Name: count, dtype: int64