In [1]:
# 개별 원소의 함수 매핑

# Series객체.apply(매핑함수)

import seaborn as sns
import pandas as pd

In [6]:
titanic = sns.load_dataset("titanic")
titanic.head()

df = titanic.loc[:, ["age", "fare"]]
df.head(3)

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250

In [7]:
def add_10(n):
    return n+10
def add_two_obj(a,b):
    return a+b

print(add_10(10))
print(add_two_obj(10,10))

20
20

In [15]:
sr1 = df["age"].apply(add_10)
df["age"].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [16]:
sr1.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [18]:
sr2 = df["age"].apply(lambda n: n+10)
sr2.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [19]:
sr3 = df["age"].apply(add_two_obj, b=10)
sr3.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [20]:
sr4 = df["age"].apply(lambda a,b : a + b, b=10)
sr4.head()

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
Name: age, dtype: float64

In [21]:
def over_thirty(age):
    return age > 10

sr_map = df["age"].map(over_thirty)
sr_map.head()

0    True
1    True
2    True
3    True
4    True
Name: age, dtype: bool

In [ ]:
sr_map2 = df["age"].map(lambda age: True if age >10 else False )
# 매개변수 람다는 age 이고 만약 age가 10보다 크면 True 아니면 False를 반환한다.
sr_map2.head()

0    True
1    True
2    True
3    True
4    True
Name: age, dtype: bool

In [25]:
print(titanic["sex"].unique())
# titanic["sex"].value_counts()
print(titanic["sex"].head())

<StringArray>
['male', 'female']
Length: 2, dtype: str
0      male
1    female
2    female
3    female
4      male
Name: sex, dtype: str

In [26]:
over_forty_dict = {
    "male": 0,
    "female" : 1
}

titanic["gender"] = titanic["sex"].map(over_forty_dict)
titanic["gender"].head()

0    0
1    1
2    1
3    1
4    0
Name: gender, dtype: int64

In [28]:
# 데이터프레임 원소에 함수 매핑

# DataFrame객체.map(매핑함수)

titanic.head()
titanic.loc[:, ["age", "fare"]]

df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [29]:
def add_10(n):
    return n+10
def add_two_obj(a,b):
    return a+b

df1 = df.map(add_10)
df1.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [30]:
df2 = df.map(lambda n : n+10)
df2.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [31]:
df3 = df.map(add_two_obj, b=10)
df3.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [32]:
df4 = df.map(lambda a, b : a + b, b=10)
df4.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [33]:
# 데이터프레임객체.apply(매핑함수, axis=0 or 1)
df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [34]:
def calculate_stats(col):
    max_val = col.max()
    min_val = col.min()
    mean_val = col.mean()
    median_val = col.median()

    df = pd.Series([
        max_val,
        min_val,
        mean_val,
        median_val
    ],index=["max","min","mean","median"])

    return df

result_df = df.apply(calculate_stats, axis = 0)
result_df.head()

              age        fare
max     80.000000  512.329200
min      0.420000    0.000000
mean    29.699118   32.204208
median  28.000000   14.454200

In [ ]:
result_sr = df.apply(lambda x : x.max() - x.min(), axis = 0) #axis 는 세로형태 열로 취급한다는 의미 / 여러가지데이터를 하나의 수로 표현하는 집계함수
result_sr

age      79.5800
fare    512.3292
dtype: float64

In [37]:
df.head(2)

    age     fare
0  22.0   7.2500
1  38.0  71.2833

In [40]:
# 데이터프레임객체.apply(매핑함수, axis=1) ->행이 매핑함수의 인수로 들어간다.

def calculate_diff_avg(row):
    diff = row.max() - row.min()
    avg = row.mean()
    return pd.Series([diff, avg], index = ["차이","평균"])

result_df2 = df.apply(calculate_diff_avg, axis = 1)
result_df2

          차이        평균
0    14.7500  14.62500
1    33.2833  54.64165
2    18.0750  16.96250
3    18.1000  44.05000
4    26.9500  21.52500
..       ...       ...
886  14.0000  20.00000
887  11.0000  24.50000
888   0.0000  23.45000
889   4.0000  28.00000
890  24.2500  19.87500

[891 rows x 2 columns]

In [ ]:
result_df3 = df.apply(
    lambda row, multiplier: pd.Series(
        [(row.max() - row.min()) * multiplier, row.mean()],
        index=["차이", "평균"]
    ), multiplier=2, axis=1)


result_df3

          차이        평균
0    29.5000  14.62500
1    66.5666  54.64165
2    36.1500  16.96250
3    36.2000  44.05000
4    53.9000  21.52500
..       ...       ...
886  28.0000  20.00000
887  22.0000  24.50000
888   0.0000  23.45000
889   8.0000  28.00000
890  48.5000  19.87500

[891 rows x 2 columns]

In [50]:
# 조건식을 만족하는 열을 필터링

df.head(3)

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250

In [ ]:
filtered_columns = df.apply(lambda x : x.mean() >30)
# mean과 fare의 평균이 30보다 큰지 확인하는 조건식.
filtered_columns

age     False
fare     True
dtype: bool

In [52]:
df.describe()

              age        fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200