In [1]:
# 열순서 변경

import pandas as pd
import seaborn as sns

In [5]:
titanic = sns.load_dataset("titanic")
titanic.head()

df = titanic.loc[:, "survived":"age"]
df.head()

   survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [8]:
columns = list(df.columns.values)
columns

['survived', 'pclass', 'sex', 'age']

In [16]:
# print(sorted(columns))
# print(sorted(columns, reverse=True))

columns_sorted = sorted(columns, reverse=False)
df_sorted = df[columns_sorted]
df_sorted.head()

    age  pclass     sex  survived
0  22.0       3    male         0
1  38.0       1  female         1
2  26.0       3  female         1
3  35.0       1  female         1
4  35.0       3    male         0

In [18]:
columns_customed = ["pclass", "sex", "age", "survived"]
df_customed = df[columns_customed]
df_customed

     pclass     sex   age  survived
0         3    male  22.0         0
1         1  female  38.0         1
2         3  female  26.0         1
3         1  female  35.0         1
4         3    male  35.0         0
..      ...     ...   ...       ...
886       2    male  27.0         0
887       1  female  19.0         1
888       3  female   NaN         0
889       1    male  26.0         1
890       3    male  32.0         0

[891 rows x 4 columns]

In [19]:
#열분리
import pandas as pd

df = pd.read_excel("./data/주가데이터.xlsx",engine="openpyxl")
df.head()

         연월일   당일종가  전일종가     시가     고가     저가     거래량
0 2018-07-02  10100   600  10850  10900  10000  137977
1 2018-06-29  10700   300  10550  10900   9990  170253
2 2018-06-28  10400   500  10900  10950  10150  155769
3 2018-06-27  10900   100  10800  11050  10500  133548
4 2018-06-26  10800   350  10900  11000  10700   63039

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연월일     20 non-null     datetime64[us]
 1   당일종가    20 non-null     int64
 2   전일종가    20 non-null     int64
 3   시가      20 non-null     int64
 4   고가      20 non-null     int64
 5   저가      20 non-null     int64
 6   거래량     20 non-null     int64
dtypes: datetime64[us](1), int64(6)
memory usage: 1.2 KB

In [21]:
df["연월일"] = df["연월일"].astype("str")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연월일     20 non-null     str
 1   당일종가    20 non-null     int64
 2   전일종가    20 non-null     int64
 3   시가      20 non-null     int64
 4   고가      20 non-null     int64
 5   저가      20 non-null     int64
 6   거래량     20 non-null     int64
dtypes: int64(6), str(1)
memory usage: 1.2 KB

In [22]:
dates = df["연월일"].str.split("-")
dates

0     [2018, 07, 02]
1     [2018, 06, 29]
2     [2018, 06, 28]
3     [2018, 06, 27]
4     [2018, 06, 26]
5     [2018, 06, 25]
6     [2018, 06, 22]
7     [2018, 06, 21]
8     [2018, 06, 20]
9     [2018, 06, 19]
10    [2018, 06, 18]
11    [2018, 06, 15]
12    [2018, 06, 14]
13    [2018, 06, 12]
14    [2018, 06, 11]
15    [2018, 06, 08]
16    [2018, 06, 07]
17    [2018, 06, 05]
18    [2018, 06, 04]
19    [2018, 06, 01]
Name: 연월일, dtype: object

In [24]:
# Series객체.str.get(인덱스)

df["연"] = dates.str.get(0)
# df["연"].head()

df["월"] = dates.str.get(1)
df["일"] = dates.str.get(2)
df.head()

          연월일   당일종가  전일종가     시가     고가     저가     거래량     연   월   일
0  2018-07-02  10100   600  10850  10900  10000  137977  2018  07  02
1  2018-06-29  10700   300  10550  10900   9990  170253  2018  06  29
2  2018-06-28  10400   500  10900  10950  10150  155769  2018  06  28
3  2018-06-27  10900   100  10800  11050  10500  133548  2018  06  27
4  2018-06-26  10800   350  10900  11000  10700   63039  2018  06  26

In [25]:
df_expand = df["연월일"].str.split("-", expand=True)
df_expand.head()

      0   1   2
0  2018  07  02
1  2018  06  29
2  2018  06  28
3  2018  06  27
4  2018  06  26