In [1]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
df = titanic.loc[:, ["age","sex","class","fare","survived"]]
df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [ ]:
df2 = pd.pivot_table(
    df,
    index = ["class","survived"],
    columns = "sex",
    values= "age",
    aggfunc = "mean",
    observed=True
)

df2

sex                 female       male
class  survived
First  0         25.666667  44.581967
       1         34.939024  36.248000
Second 0         36.000000  33.369048
       1         28.080882  16.022000
Third  0         23.818182  27.255814
       1         19.329787  22.274211

In [5]:
df_stacked = df2.stack()
df_stacked

class   survived  sex
First   0         female    25.666667
                  male      44.581967
        1         female    34.939024
                  male      36.248000
Second  0         female    36.000000
                  male      33.369048
        1         female    28.080882
                  male      16.022000
Third   0         female    23.818182
                  male      27.255814
        1         female    19.329787
                  male      22.274211
dtype: float64

In [6]:
df_sunstacked = df2.unstack()
df_sunstacked

sex          female                  male
survived          0          1          0          1
class
First     25.666667  34.939024  44.581967  36.248000
Second    36.000000  28.080882  33.369048  16.022000
Third     23.818182  19.329787  27.255814  22.274211

In [7]:
df2

sex                 female       male
class  survived
First  0         25.666667  44.581967
       1         34.939024  36.248000
Second 0         36.000000  33.369048
       1         28.080882  16.022000
Third  0         23.818182  27.255814
       1         19.329787  22.274211

In [8]:
df2.unstack(level=0)

sex          female                             male
class         First     Second      Third      First     Second      Third
survived
0         25.666667  36.000000  23.818182  44.581967  33.369048  27.255814
1         34.939024  28.080882  19.329787  36.248000  16.022000  22.274211

In [9]:
df2.unstack(level=1)

sex          female                  male
survived          0          1          0          1
class
First     25.666667  34.939024  44.581967  36.248000
Second    36.000000  28.080882  33.369048  16.022000
Third     23.818182  19.329787  27.255814  22.274211