In [2]:
# DataFrame객체.melt(id_vars=[],value_vars="")

import pandas as pd

In [3]:
df = pd.DataFrame({
    "name":["John","Mary"],
    "city":["New York","Los Angeles"],
    "Age" : [28,32],
    "Salary": [50000,60000]
})
df

   name         city  Age  Salary
0  John     New York   28   50000
1  Mary  Los Angeles   32   60000

In [4]:
df_melted = df.melt(
    id_vars = ["name","city"],
    var_name = "Attribue",
    value_name = "value"
)

df_melted

   name         city Attribue  value
0  John     New York      Age     28
1  Mary  Los Angeles      Age     32
2  John     New York   Salary  50000
3  Mary  Los Angeles   Salary  60000

In [5]:
df_wide = pd.DataFrame({
    "company": ["Google", "Yahoo"],
    "Income_2019": [100000, 50000],
    "Income_2020": [120000, 55000],
    "Expense_2019" : [50000, 30000],
    "Expense_2020" : [60000, 35000],
})
df_wide

  company  Income_2019  Income_2020  Expense_2019  Expense_2020
0  Google       100000       120000         50000         60000
1   Yahoo        50000        55000         30000         35000

In [7]:
df_long = pd.wide_to_long(
    df_wide,
    stubnames=["Income","Expense"],
    i="Company",
    j="Year",
    sep="_",
    suffix="\d+"
)

df_long = df_long.reset_index()
df_long

<>:7: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:7: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\wm032\AppData\Local\Temp\ipykernel_4904\3612007701.py:7: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  suffix="\d+"

KeyError: "None of [Index(['Company'], dtype='str')] are in the [columns]"