In [1]:
import pandas as pd

In [2]:
dict_data = {
    "c0" : [1,2,3],
    "c1" : [4,5,6],
    "c2" : [7,8,9],
    "c3" : [10,11,12],
    "c4" : [13,14,15]
}

df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [3]:
# pandas.DataFrame(2차원배열,
#                  index=행 인덱스 배열,
#                  colums = 열 이름 배열
#                 )

arr = [
    [15,'남','덕영중'],
    [17, '여', '수리중']
]

df = pd.DataFrame(arr,index=['준서','예은'], columns=['나이','성별','학교'])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [7]:
print(list(df.index))
print(list(df.columns))

['준서', '예은']
['나이', '성별', '학교']

In [8]:
# 행 인덱스 변경 
# DataFrame 객체.index = 행인덱스배열
# DataFrame 객체.columns = 열인덱스배열

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [9]:
df.index=["학생1","학생2"]
print(df)

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [11]:
df.columns = ["연령","남녀","소속 "]
print(df)

     연령 남녀  소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [12]:
# 행 인덱스 변경 : DataFrame객체.rename(index = {기존 인덱스:새 인덱스})
# 열 인덱스 변경 : DataFrame객체.rename(columns = {기존 이름:새이름})

import pandas as pd

matrix = [
    [15,"남","덕영중"],
    [17, "여","수리중"]
]

df = pd.DataFrame(matrix, index =["준서","예은"],columns=["나이","성별","학교"] )
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [ ]:
df = df.rename(columns = {
    "나이":"연령",
    "성별":"남녀",
    "학교":"소속"
    })
df

# 리네임 하고난 후에는 무조건 재할당해줘야함!

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [18]:
df = df.rename(index={
    "준서" : "학생1",
    "예은" : "학생2",
})

df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [20]:
# 행/열 삭제

# 행삭제 :  DataFrame객체.drop(행인덱스 또는 배열, axis=0, axis="index")
# 열삭제 :  DataFrame객체.drop(열이름 또는 배열, axis=1, axis="columns")


import pandas as pd

exam_data = {
    "수학" : [90,80,70],
    "영어" : [98,89,95],
    "음악" : [85,95,100],
    "체육" : [100,90,90]
}

df = pd.DataFrame(exam_data, index = ['서준','우현','민아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [22]:
df2 = df.copy()
df2 = df2.drop("우현")
df2

    수학  영어   음악   체육
서준  90  98   85  100
민아  70  95  100   90

In [24]:
df3 = df.copy()
print(df3)
df3 = df.drop(["우현","민아"])
print(df3)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90
    수학  영어  음악   체육
서준  90  98  85  100

In [25]:
df4 = df.copy()
df4 = df4.drop(["우현","민아"], axis = "index")
df4

    수학  영어  음악   체육
서준  90  98  85  100

In [26]:
df5 = df.copy()
df5 = df5.drop(index=["우현"])
df5

    수학  영어   음악   체육
서준  90  98   85  100
민아  70  95  100   90

In [27]:
import pandas as pd

exam_data = {
    "수학" : [90,80,70],
    "영어" : [98,89,95],
    "음악" : [85,95,100],
    "체육" : [100,90,90]
}

df = pd.DataFrame(exam_data, index = ['서준','우현','민아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [30]:
df2 = df.copy()
df2 = df2.drop("수학",axis=1)
df2

    영어   음악   체육
서준  98   85  100
우현  89   95   90
민아  95  100   90

In [32]:
df2 = df.copy()
df2 = df2.drop("수학",axis="columns")
df2

    영어   음악   체육
서준  98   85  100
우현  89   95   90
민아  95  100   90

In [ ]:
df3 = df.copy()
df3 = df3.drop(["영어","음악"],axis=1) # 2개이상 지울떄는 리스트만들어서 지울것.
df3

    수학   체육
서준  90  100
우현  80   90
민아  70   90

In [34]:
df4 = df.copy()
df4 = df4.drop({"영어","음악"}, axis="columns")
df4

    수학   체육
서준  90  100
우현  80   90
민아  70   90

In [35]:
df5 = df.copy()
df5 = df5.drop(columns=["수학"])
df5

    영어   음악   체육
서준  98   85  100
우현  89   95   90
민아  95  100   90

In [36]:
# 행선택

import pandas as pd

exam_data = {
    "수학" : [90,80,70],
    "영어" : [98,89,95],
    "음악" : [85,95,100],
    "체육" : [100,90,90]
}

df = pd.DataFrame(exam_data, index = ['서준','우현','민아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [40]:
label1 = df.loc["서준"] #서준에 해당하는 모든 행을 가져왓음.
print(type(label1))
print(label1)

<class 'pandas.Series'>
수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [42]:
position1 = df.iloc[0]
print(position1)
print(type(position1))

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [43]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [44]:
label2 = df.loc[["서준","우현"]]
print(label2)
print(type(label2))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.DataFrame'>

In [45]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [46]:
label3 = df.loc[["서준"]]
print(label3)
print(type(label3))

    수학  영어  음악   체육
서준  90  98  85  100
<class 'pandas.DataFrame'>

In [48]:
position2 = df.iloc[[0,2]]
print(position2)
print(type(position2))

    수학  영어   음악   체육
서준  90  98   85  100
민아  70  95  100   90
<class 'pandas.DataFrame'>

In [49]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [51]:
label3 = df.loc["서준":"민아"]
print(label3)

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [52]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [55]:
position3 = df.iloc[0:2]
print(position3)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [57]:
# 열1개 선택 : DataFrame객체["열이름"] 또는 DataFrame객체.열이름

exam_data = {
    "이름" : ['서준','우현','민아'],
    "수학" : [90,80,70],
    "영어" : [98,89,95],
    "음악" : [85,95,100],
    "체육" : [100,90,90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [58]:
math1 = df["수학"]
math1

0    90
1    80
2    70
Name: 수학, dtype: int64

In [59]:
english = df.영어
english

0    98
1    89
2    95
Name: 영어, dtype: int64

In [60]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [62]:
music_gym = df[["음악","체육"]]
music_gym

    음악   체육
0   85  100
1   95   90
2  100   90

In [ ]:
df1 = df['수학']
df1.shape # (3,) -> 3행
print(df1)

0    90
1    80
2    70
Name: 수학, dtype: int64

In [ ]:
df2 = df[["수학"]]
df2.shape #(3,1) -> 3행 1열
print(df2)

   수학
0  90
1  80
2  70

In [69]:
# 범위 슬라이승 : DataFrame객체.iloc[시작인덱스:끝인덱스:간격]

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [71]:
df.iloc[::2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  민아  70  95  100   90

In [72]:
# 원소선택
# 인덱스이름 : DataFrame객체.loc[행인덱스, 열이름]
# 정수위치인덱스: DataFrame객체.iloc[행번호,열번호]

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [75]:
df = df.set_index("이름")

In [76]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [81]:
a = df.loc["서준","음악"]
df.iloc[0,2]

np.int64(85)

In [82]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [83]:
df.loc["서준",['음악','체육']]

음악     85
체육    100
Name: 서준, dtype: int64

In [84]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [85]:
df.iloc[0,[2,3]]

음악     85
체육    100
Name: 서준, dtype: int64

In [86]:
df.loc["서준", '음악':'체육']

음악     85
체육    100
Name: 서준, dtype: int64

In [87]:
df.iloc[0, 2:]

음악     85
체육    100
Name: 서준, dtype: int64

In [88]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [90]:
df.loc[["서준","우현"],["음악","체육"]]

    음악   체육
이름
서준  85  100
우현  95   90

In [91]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [92]:
df.iloc[[0,1],[2,3]]

    음악   체육
이름
서준  85  100
우현  95   90

In [93]:
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [95]:
df.loc["서준":"우현", "음악":"체육"]

    음악   체육
이름
서준  85  100
우현  95   90

In [96]:
df.iloc[0:2, 2:]

    음악   체육
이름
서준  85  100
우현  95   90

In [97]:
# 열추가
# 열추가 : DataFrame객체["추가하려는 열 이름"] = 데이터값
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [99]:
exam_data = {
    "이름" : ['서준','우현','민아'],
    "수학" : [90,80,70],
    "영어" : [98,89,95],
    "음악" : [85,95,100],
    "체육" : [100,90,90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [100]:
df["국어"] = 80
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  민아  70  95  100   90  80

In [102]:
df["미술"] = [80,90,100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  민아  70  95  100   90  80  100

In [104]:
# 행 추가

# 행추가 : DataFrame객체.loc['새로운행이름'] = 데이터값 또는 배열

exam_data = {
    "이름" : ['서준','우현','민아'],
    "수학" : [90,80,70],
    "영어" : [98,89,95],
    "음악" : [85,95,100],
    "체육" : [100,90,90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [106]:
print(df.loc[0:2])
print(df.iloc[0:2])

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90
   이름  수학  영어  음악   체육
0  서준  90  98  85  100
1  우현  80  89  95   90

In [107]:
df.loc[3] = 0
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90
3   0   0   0    0    0

In [108]:
df.loc[4] = ['동규',90,80,70,60]
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

In [ ]:
df.loc["5"] = df.loc[3]
df

    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   민아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5   0   0   0    0    0
5    0   0   0    0    0

In [1]:
# 원소 값 변경

import pandas as pd

exam_data = {
    "이름" : ['서준','우현','민아'],
    "수학" : [90,80,70],
    "영어" : [98,89,95],
    "음악" : [85,95,100],
    "체육" : [100,90,90]
}

df = pd.DataFrame(exam_data)

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [2]:
df = df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [7]:
df.iloc[0,3] = 80
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
민아  70  95  100  90

In [14]:
df.loc["서준","체육"] = 90
df

    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
민아  70  95  100  90

In [16]:
df.loc["서준",["음악","체육"]] = 90
df

    수학  영어   음악  체육
이름
서준  90  98   90  90
우현  80  89   95  90
민아  70  95  100  90

In [17]:
df.loc["서준",["음악","체육"]] = 100,50
df

    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
민아  70  95  100  90

In [18]:
# 행과 열의 위치 바꾸기

# 행, 열 바꾸기 : DataFrame객체.transpose() 또는 T

import pandas as pd

exam_data = {
    "이름" : ['서준','우현','민아'],
    "수학" : [90,80,70],
    "영어" : [98,89,95],
    "음악" : [85,95,100],
    "체육" : [100,90,90]
}

df = pd.DataFrame(exam_data)

df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [19]:
df = df.transpose()
df

      0   1    2
이름   서준  우현   민아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [21]:
df = df.T
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90