In [1]:
import pandas as pd

exam_data = {
    "이름" : ['서준','우현','민아'],
    "수학" : [90,80,70],
    "영어" : [98,89,95],
    "음악" : [85,95,100],
    "체육" : [100,90,90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  민아  70  95  100   90

In [2]:
ndf = df.set_index(["이름"])
ndf

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
민아  70  95  100   90

In [5]:
ndf2=ndf.set_index("음악")
ndf2

     수학  영어   체육
음악
85   90  98  100
95   80  89   90
100  70  95   90

In [6]:
ndf3 = ndf.set_index(["수학","음악"])
ndf3

        영어   체육
수학 음악
90 85   98  100
80 95   89   90
70 100  95   90

In [7]:
ndf4 = ndf.set_index(["수학","음악","영어","체육"])
ndf4

Empty DataFrame
Columns: []
Index: [(90, 85, 98, 100), (80, 95, 89, 90), (70, 100, 95, 90)]

In [8]:
# 행인덱스 재배열

# 데이터프레임객체.reindex(인덱스배열)

dict_data = {
    "c0" : [1,2,3],
    "c1" : [4,5,6],
    "c2" : [7,8,9],
    "c3" : [10,11,12],
    "c4" : [13,14,15]
}

df = pd.DataFrame(dict_data,index=["r0","r1","r2"])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [ ]:

# 데이터프레임객체.reindex(인덱스배열)

new_index = ["r0","r1","r2","r3","r4"]
ndf = df.reindex(new_index)
ndf

     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN

In [10]:
new_index = ["r0","r1","r2","r3","r4"]

ndf2 = df.reindex(new_index, fill_value=0)
ndf2

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [13]:
# 행인덱스 초기화

dict_data = {
    "c0" : [1,2,3],
    "c1" : [4,5,6],
    "c2" : [7,8,9],
    "c3" : [10,11,12],
    "c4" : [13,14,15]
}

df = pd.DataFrame(dict_data, index=["r0","r1","r2"])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [14]:
ndf = df.reset_index()
ndf

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [15]:
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [16]:
ndf2 = df.reset_index(names=["C00"])
ndf2

  C00  c0  c1  c2  c3  c4
0  r0   1   4   7  10  13
1  r1   2   5   8  11  14
2  r2   3   6   9  12  15

In [17]:
ndf3 = df.reset_index(drop=True)
ndf3

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [21]:
# 행 인덱스를 기준으로 데이터프레임 정렬

# 행 인덱스 기준 정렬: DataFrame객체.sort_index()

dict_data = {
    "c0" : [1,2,3],
    "c1" : [4,5,6],
    "c2" : [7,8,9],
    "c3" : [10,11,12],
    "c4" : [13,14,15]
}


df = pd.DataFrame(dict_data, index=["c0","c1","c2"])
df

    c0  c1  c2  c3  c4
c0   1   4   7  10  13
c1   2   5   8  11  14
c2   3   6   9  12  15

In [23]:
ndf = df.sort_index(ascending=False)
ndf

    c0  c1  c2  c3  c4
c2   3   6   9  12  15
c1   2   5   8  11  14
c0   1   4   7  10  13

In [ ]:
import pandas as pd

dict_data = {
    "c0" : [1,2,3],
    "c1" : [4,5,6],
    "c2" : [7,8,9],
    "c3" : [10,11,12],
    "c4" : [13,14,15]
}

df = pd.DataFrame(dict_data, index=["r0","r1","r2"])
df

ndf = df.sort_index(ascending=False) #오름차순 정렬을 하겠다라는 함수 ascending=True
ndf

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [8]:
dict_data = {
    "c0" : [1,2,3],
    "c1" : [4,5,6],
    "c2" : [7,8,9],
    "c3" : [10,12,12],
    "c4" : [13,14,15]
}

df = pd.DataFrame(dict_data, index=["r0","r1","r2"])
df

ndf = df.sort_values(by="c1", ascending=False)
ndf

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  12  14
r0   1   4   7  10  13

In [ ]:
ndf3 = df.sort_values(by=["c3","c4"],ascending=[False,True])
#c3은 내림차순 c4는 오름차순으로 하겟다라는 의미
ndf3
#앞의 기준이 같을떄 뒤에c4가 정렬이 된다.

    c0  c1  c2  c3  c4
r1   2   5   8  12  14
r2   3   6   9  12  15
r0   1   4   7  10  13